name: Update Streak Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          options: user=Techside-Pragyan&theme=tokyonight&hide_border=true
          path: assets/streak-stats.svg
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/streak-stats.svg
          git diff --staged --quiet || (git commit -m "chore: update streak stats [skip ci]" && git push)
